all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: nokia.srlinux.srlinux
  hosts:
    srl1:
      ansible_host: 172.20.20.5
    srl2:
      ansible_host: 172.20.20.4
