all:
  vars:
    ansible_user: admin
    ansible_password: admin
    ansible_network_os: nokia.srlinux.srlinux
    ansible_connection: ansible.netcommon.httpapi
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_httpapi_port: 443
  hosts:
    srl1:
      ansible_host: 172.20.20.5
    srl2:
      ansible_host: 172.20.20.4
